language: r
warnings_are_errors: true

cran: http://cran.rstudio.com

r_binary_packages:
  - RCurl
  - knitr
r_github_packages:
  - hadley/bookdown

apt_packages:
  - texlive-xetex
  - fonts-inconsolata

script:
  - xelatex -version
  - pandoc --version
  - pandoc-citeproc --version

  # Update font-cache to include inconsolata
  - sudo fc-cache -fv

  # Create PDF file
  - Rscript  './report/build-report.r'

notifications:
  email:
    on_success: change
    on_failure: change
