language: c

env:
- WARNINGS_ARE_ERRORS=1

before_install:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- "./travis-tool.sh bootstrap"

install:
- mkdir $HOME/pandoc
- export PATH="$HOME/pandoc:$PATH"
- curl -O https://s3.amazonaws.com/rstudio-buildtools/pandoc-1.12.3.zip
- unzip -j pandoc-1.12.3.zip pandoc-1.12.3/linux/debian/x86_64/pandoc -d $HOME/pandoc
- chmod +x $HOME/pandoc/pandoc
- pandoc --version

# Install jekyll
  - travis_retry gem install jekyll mime-types

# Install R packages
- "./travis-tool.sh github_package   hadley/devtools"
- "./travis-tool.sh github_package   rstudio/rmarkdown hadley/bookdown"
- "./travis-tool.sh r_binary_install knitr"
- "./travis-tool.sh r_binary_install RCurl"
- mkdir ~/.R
- cp Makevars ~/.R

script: jekyll build

after_failure:
- "./travis-tool.sh dump_logs"

deploy:
  provider: s3
  access_key_id: AKIAJXAGPD4HZ5IORX2Q
  secret_access_key:
    secure: gaZ9Ds61sQwp0yG5wS5LGA1/DYCzbQyiW/rvsaw3GWLbK/QZhByoki+TqEvW+/DGBShQ3Sc4+ZIpQdOCwZ9OIMRG/Tu8GHxJX2fSheW5soH5l5Pm78SUoAIw+d53wDaIfM12xye05L1HVjrmWqID7Hhn+p1U1znKr9k5I4in1Jo=
  bucket: r-pkgs.had.co.nz
  endpoint: io.github.niranjv.s3-website-us-east-1.amazonaws.com
  upload-dir: ucscamsms2015
  local_dir: report
  detect_encoding: true
  skip_cleanup: true

notifications:
  email:
    on_success: change
    on_failure: change
