# Based on:
# https://github.com/craigcitro/r-travis/blob/master/sample.travis.yml
# https://github.com/hadley/r-pkgs/blob/master/.travis.yml

language: c

env:
- WARNINGS_ARE_ERRORS=1

before_install:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- "./travis-tool.sh bootstrap"

install:
# Install binary pandoc from RStudio
- export PATH="$HOME/pandoc:$PATH"
- mkdir $HOME/pandoc
- curl -O https://s3.amazonaws.com/rstudio-buildtools/pandoc-1.12.3.zip
- unzip -j pandoc-1.12.3.zip pandoc-1.12.3/linux/debian/x86_64/* -d $HOME/pandoc
- chmod +x $HOME/pandoc/pandoc
- pandoc --version

# Install xetex and inconsolata font
- sudo apt-get install texlive-xetex
- sudo apt-get install fonts-inconsolata
- sudo fc-cache -fv

# Install R packages
- "./travis-tool.sh r_binary_install knitr RCurl"
- "./travis-tool.sh github_package   hadley/devtools hadley/bookdown"
- "./travis-tool.sh github_package   niranjv/schedulr@develop"

script:
- Rscript report/build-report.r

after_failure:
- "./travis-tool.sh dump_logs"

deploy:
  provider: s3
  access_key_id: AKIAJXAGPD4HZ5IORX2Q
  secret_access_key:
    secure: i7JNkQK84DAxHFZjSTFWYf5+3WcI5Ku09ZMPXfrFjKeIwWcsVHAggSUzyWq/oeNpWxkVLFJdpKIZnddCoOzTxb5qbyrKtyNV76TWoGcAsX78hMnAAtpysLDK3Pw0SLGJoZUvrg/EMMBbfftMfmRyphPh0qHKch//1g+k1PyEtOw=
  acl: public_read
  bucket: io.github.niranjv
  detect_encoding: true
  skip_cleanup: true
  local-dir: output
  upload-dir: ucscamsms2015
  on:
    repo: niranjv/ucscamsms2015
    branch: develop

notifications:
  email:
    on_success: change
    on_failure: change
