language: r
warnings_are_errors: true

cran: http://cran.rstudio.com

r_binary_packages:
  - RCurl
  - knitr
r_github_packages:
  - hadley/devtools
  - hadley/bookdown

apt_packages:
  - texlive-xetex

notifications:
  email:
    on_success: change
    on_failure: change
