
# Code to generate results in Chapters 2 and 3

This is the code to generate the plots and tables in Chapters 2 and 3


```{r cache=FALSE, echo=FALSE}
  knitr::read_chunk('../bin/plot.R')
```

```{r init, eval=FALSE, tidy=TRUE}
```

```{r 1instance-deterministic-runtimes, eval=FALSE, tidy=TRUE}
```

```{r 1instance-stochastic-runtimes-known-dist-100tasks, eval=FALSE, tidy=TRUE}
```

```{r 1instance-stochastic-runtimes-known-dist-250tasks, eval=FALSE, tidy=TRUE}
```

```{r 1instance-stochastic-runtimes-known-dist-500tasks, eval=FALSE, tidy=TRUE}
```

```{r 1instance-stochastic-runtimes-known-dist-1000tasks, eval=FALSE, tidy=TRUE}
```

```{r 1instance-stochastic-runtimes-known-dist-10tasks, eval=FALSE, tidy=TRUE}
```

```{r 1instance-stochastic-runtimes-known-dist-25tasks, eval=FALSE, tidy=TRUE}
```

```{r 1instance-stochastic-runtimes-known-dist-50tasks, eval=FALSE, tidy=TRUE}
```

```{r 1instance-stochastic-runtimes-known-dist-75tasks, eval=FALSE, tidy=TRUE}
```

```{r SA.validation, eval=FALSE, tidy=TRUE}
```


# Code for *schedulr* R package

This is the code for the schedulr R package

```{r echo=FALSE, eval=TRUE, include=FALSE, tidy=TRUE}

  library(RCurl)
  library(knitr)

  filename <- 'code.r'
  if (file.exists(filename)) file.remove(filename)

  curlPerform(url = "https://raw.githubusercontent.com/niranjv/schedulr/develop/R/simulated-annealing.R",
              writefunction = function(txt, ...) {
                                   cat(txt, "\n", file=filename, append=T)
                                   return(TRUE)
                              })

  read_chunk(path=filename, labels=c('all'))
  on.exit(unlink(filename))
```

```{r eval=FALSE}
  <<all>>
```
